
name: Conventional Commits

on:
  push:

jobs:
  build:
    name: Conventional Commits
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: gentleseal/action-conventional-commits@master
        with:
          valid-commit-types: >
            [
              "feat",
              "docs",
              "style",
              "refactor",
              "test",
              "build",
              "ci",
              "chore",
              "revert",
              "merge",
              "wip",
              "enh"
            ]