
name: Conventional Commits

on: 
  pull_request_target:
    types:
      - opened
      - reopened
      - edited

jobs:
  build:
    name: Conventional Commits
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: gentleseal/action-conventional-commits@master
        with:
          valid-commit-types: >
            [
              "feat:",
              "fix:",
              "docs:"
              ]


