name: Comment

on: 
  pull_request:
    types: [opened]
  

jobs:
  example_comment_pr:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Comment PR
        uses: thollander/actions-comment-pull-request@v2
        with:
          message: |
            :bangbang: When you make a PR on the main branch, you always have to choose exactly one label. :bangbang:	

