name: Comment
on: pull_request

jobs:
  example_comment_pr:
    runs-on: ubuntu-latest
    name: An example job to comment a PR
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Comment PR
        uses: thollander/actions-comment-pull-request@v2
        with:
          message: |
            :warning: When you make a PR on the main branch, you always have to choose only one label. :warning:

      - name: Check label
        uses: mheap/github-action-required-labels@v2
        with:
         mode: exactly
         count: 1
         labels: "version:patch, version:minor, versuin:major, no_release"
         add_comment: true