on: 
  pull_request:
    types: [opened]

jobs:
  example_comment_pr:
    runs-on: ubuntu-latest
    name: An example job to comment a PR
    steps:
      - name: Checkout
        uses: actions/checkout@v1

      - name: Comment PR
        uses: allthatjazzleo/actions-pull-request-add-comment@master
        if: github.event_name == 'pull_request'
        with:
          message: 'yoyo🤙🏻'
          # message: "echo ${{ github.event.comment.body }}" dynamic message based on comment
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}