name: PR labels

on:
  pull_request:
    types: [labeled, unlabeled, opened, edited, synchronize]

jobs:
  example_comment_pr:
    runs-on: ubuntu-latest
    steps:

      - name: Comment PR
        uses: thollander/actions-comment-pull-request@v2
        with:
          message: |
            :bangbang: When you make a PR on the main branch, you always have to choose exactly one label. :bangbang:	

  Check-label-job:
    runs-on: ubuntu-latest
    needs: example_comment_pr
    steps:
      - name: Check labels
        uses: docker://agilepathway/pull-request-label-checker:latest
        with:
          one_of: version:major,version:minor,version:patch,no_release
          mode: exactly
          count: 1
          repo_token: ${{ secrets.GITHUB_TOKEN }}

  # label-checker:
  #   runs-on: ubuntu-latest
  #   needs: example_comment_pr
  #   steps:
  #   - name: Checking labels 
  #     uses: mheap/github-action-required-labels@v2
  #     env:
  #       GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  #     with:
  #       mode: exactly
  #       count: 1
  #       labels: "version:patch, version:minor, version:major, no_release"
  some_job:
    runs-on: ubuntu-latest
    needs: Check-label-job
    steps:
      - name: Hello
        run: echo "Hello everyone"
