name: Pull Request label checker

on: 
  pull_request:
    types: [ opened ]

jobs:
  Checking-pr-labels:
    runs-on: ubuntu-latest
    steps:
      - name: Check label
        uses: mheap/github-action-required-labels@v2
        with:
          mode: exactly
          count: 1
          labels: "version:patch, version:minor, versuin:major, no_release"
          add_comment: true
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}