name: Pull Request Labels
on:
  pull_request
jobs:
  label:
    runs-on: ubuntu-latest
    steps:
      - id: check-labels
        uses: mheap/github-action-required-labels@v2
        with:
          mode: exactly
          count: 1
          labels: "version:patch, version:minor, version:major, no_release"
          exit_type: success