name: Pull Request Labels
on:
  pull_request:

jobs:
  checking-labels:
    runs-on: ubuntu-latest
    steps:
      - uses: mheap/github-action-required-labels@v2
        with:
          mode: exactly
          count: 1
          labels: "version:patch, version:minor, version:major"