name: PR labels

on:
  pull_request:
    types: [labeled, unlabeled, opened, edited, synchronize]

jobs:
  label-checker:
    runs-on: ubuntu-latest
    steps:
    - name: Verify Pull Request Labels
      uses: emmenko/action-verify-pr-labels@master
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}