name: PR labels

on:
  pull_request:
    types: [labeled, unlabeled, opened, edited, synchronize]

jobs:
  label-checker:
    runs-on: ubuntu-latest
    steps:
    - name: No labels
      uses: mheap/github-action-required-labels@v2
      with:
        mode: exactly
        count: 0
        labels: "do not merge"

    - uses: mheap/github-action-required-labels@v2
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        mode: exactly
        count: 1
        labels: "version:patch, version:minor, version:major, no_release"
        add_comment: true
