name: image taging 

on:
  pull_request:
    types: [ closed ]
    branches: [main]

jobs:
  new_version:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Comment PR
      uses: thollander/actions-comment-pull-request@v2
      with:
        message: |
          neka PR poruka

    - uses: actions/setup-node@v3
      with:
       node-version: 16
    - name: Looking for minor changes 
      if:  ${{contains(github.event.pull_request.labels.*.name, 'version:minor')}}
      run: echo "NEW_VERSION=$(npm version minor --no-git-tag-version --tag-version-prefix="")" >> $GITHUB_ENV
    - name: Looking for major changes
      if:  ${{contains(github.event.pull_request.labels.*.name, 'version:major')}}
      run: echo "NEW_VERSION=$(npm version major --no-git-tag-version --tag-version-prefix="")" >> $GITHUB_ENV

    - name: Looking for patch changes
      if: ${{contains(github.event.pull_request.labels.*.name, 'version:patch')}}
      run: echo "NEW_VERSION=$(npm version patch --no-git-tag-version --tag-version-prefix="")" >> $GITHUB_ENV
    - name: check package json
      run: |
          git status
          cat package.json
    - name: new version
      run: echo $NEW_VERSION

    - name: push-tag
      run: |
        git tag $NEW_VERSION && git push --tags
        git add .
        git commit -m "new version package json"
        git push  



# - name: get-npm-version
#   id: package-version
#   uses: martinbeentjes/npm-get-version-action@main



# name: Release

# on: 
#   push:
#     branches: [main]
  

# jobs:
#   Release:
#     runs-on: ubuntu-latest
#     steps:
#       - uses: actions/checkout@v3
#         with:
#           fetch-depth: 0
#       - name: Release tagging
#         id: versioning
#         uses: PaulHatch/semantic-version@v4.0.2
#         with:
#           branch: main
#           tag_prefix: "v"
#           major_pattern: "BREAKING CHANGES"
#           minor_pattern: "feat:"
#           format: "v${major}.${minor}.${patch}"
      
#       - name: Create Release
#         if: ${{ !startsWith(github.ref, 'refs/tags') }}
#         uses: actions/create-release@v1
#         env:
#           GITHUB_TOKEN: ${{ secrets.github_token}}
#         with:
#           tag_name: ${{ steps.versioning.outputs.version }}
#           release_name: ${{ steps.versioning.outputs.version }}
#           prerelease: false
#------------------------------------------------------------
# name: release
# on:
#   push:
#     branches:
#       - main
#   pull_request:
#     types:
#       - labeled

# jobs:
#   release:
#     runs-on: ubuntu-latest
#     steps:
#       - uses: actions/checkout@v2
#       # Bump version on merging Pull Requests with specific labels.
#       # (bump:major,bump:minor,bump:patch)
#       - uses: haya14busa/action-bumpr@v1
# name: release
# on:
#   push:
#     branches:
#       - main

# jobs:
#   release-on-push:
#     runs-on: ubuntu-latest
#     env:
#       GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
#     steps:
#       - name: Release
#         uses: rymndhng/release-on-push-action@master
#         with:
#           bump_version_scheme: patch # default change 
#           use_github_release_notes: true


